Added color verbose, fixed both cfg methods. Fixed intialisation stack

diff --git a/mod/etc/init.d/S8108networking_mount b/mod/etc/init.d/S8108networking_mount
--- a/mod/etc/init.d/S8108networking_mount
+++ b/mod/etc/init.d/S8108networking_mount
@@ -6,33 +6,58 @@
 
         source /etc/preinit
         script_init
+        
+        # Reset
+        Color_Off="\[\033[0m\]"       # Text Reset
+
+        # Regular Colors
+        Black="\[\033[0;30m\]"        # Black
+        Red="\[\033[0;31m\]"          # Red
+        Green="\[\033[0;32m\]"        # Green
+        Yellow="\[\033[0;33m\]"       # Yellow
+        Blue="\[\033[0;34m\]"         # Blue
+        Purple="\[\033[0;35m\]"       # Purple
+        Cyan="\[\033[0;36m\]"         # Cyan
+        White="\[\033[0;37m\]"        # White
 
         [ -f "/media/hakchi/retroarch-mounted.cfg" ] && mv -f "/media/hakchi/retroarch-mounted.cfg" "/etc/libretro/"
         [ -f "/media/hakchi/network-mount.cfg" ] && mv -f "/media/hakchi/network-mount.cfg" "/etc/"
 
         if [ -f "/etc/network-mount.cfg" ]; then #Just incase some one fucks up
-        
-            source /etc/network-mount.cfg
-            [ "$mount_use_ra_cfg" == "true" ] && source /etc/libretro/retroarch-mounted.cfg
-            
-            trueip="$(echo "$ra_mount_address" | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}")"
-            i=1
-            while [ "$i" -le 60 ]; do #60 Second Ping test
-              echo "Ping Test Number $i against IP address: $trueip" > /dev/tty0
-              ping -c 1 "$trueip"
-              rc=$?
-              sleep 1
-              [ "$(cat /dev/clovercon1 | grep 0800)" ] && exit 1
-              if [ $rc = 0 ] ; then
-                echo "Ping Test Success!" > /dev/tty0
-                i=666
-              else
-                i="$((i+1))"
-              fi
-            done
-            [ $rc = 0 ] || exit 1
             
             if ([ "$ra_mount_enable" == "true" ] && [ ! -z "${ra_mount_address// }" ]) || ([ "$mount_enable" == "true" ] && [ ! -z "${mount_address// }" ]); then
+            
+                echo -e "${Green} ***************************" > /dev/tty0
+                echo -e "${Green} ***Hakchi Networking Mod***" > /dev/tty0
+                echo -e "${Green} ***************************" > /dev/tty0
+            
+                source /etc/network-mount.cfg
+                [ "$mount_use_ra_cfg" == "true" ] && source /etc/libretro/retroarch-mounted.cfg
+                
+                if [ "$mount_use_ra_cfg" == "true" ]; then
+                  trueip="$(echo "$ra_mount_address" | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}")"
+                else
+                  trueip="$(echo "$mount_address" | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}")"
+                fi
+                
+                echo -e "${White} Connecting to${Yellow} $trueip..." > /dev/tty0
+                
+                i=1
+                while [ "$i" -le 30 ]; do #30 Second Ping test
+                  echo "Connection Attempt $i/30" > /dev/tty0
+                  ping -c 1 "$trueip"
+                  rc=$?
+                  sleep 1
+                  [ "$(cat /dev/clovercon1 | grep 0800)" ] && exit 1
+                  if [ $rc = 0 ] ; then
+                    echo -e "${Green} Connected to network!${White}" > /dev/tty0
+                    i=666
+                  else
+                    i="$((i+1))"
+                  fi
+                done
+                [ $rc = 0 ] || exit 1
+            
                 mkdir -p -v /var/mount &> /dev/tty0
                 if [ "$ra_mount_enable" == "true" ]; then
                     if [ "$ra_mount_vers" -gt "0" ]; then
@@ -50,18 +75,18 @@
             fi
             
             if mountpoint -q /var/mount; then #If false, we fucked up.
-                echo "[NetMount] Mounted network drive" &> /dev/tty0
+                echo -e "{Green}[NetMount] Mounted network drive" &> /dev/tty0
                 if [ "$mount_saves" == "true" ]; then
                     [ ! -d "/var/mount/saves" ] && mkdir -p /var/mount/saves 
-                    echo "[NetMount] Mounted saves on network share" &> /dev/tty0
+                    echo -e "{Green}[NetMount] Mounted saves on network share${Color_Off}" &> /dev/tty0
                     #Overmount something && echo "[NetMount] Mounted saves on network share"
                 fi
                 if [ ! -d "/var/mount/games" ]; then
-                    echo "[NetMount] Mounted games on network share" &> /dev/tty0
+                    echo -e "{Green}[NetMount] Mounted games on network share${Color_Off}" &> /dev/tty0
                     #Overmount something && echo "[NetMount] Mounted games on network share"
                 fi
             else
-                echo "[NetMount] [FAIL] Failed to mount network!" &> /dev/tty0
+                echo -e "{Red}[NetMount] [FAIL] Failed to mount network!${Color_Off}" &> /dev/tty0
             fi
         fi
         
